name: ci-windows
on:
  push:
    branches:
      - main
  pull_request:
env:
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: "~1.21.1"
jobs:
  windows-test-race:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.DEFAULT_GO_VERSION }}
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Module cache
      uses: actions/cache@v3
      env:
        cache-name: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    - name: Run tests with race detector
      run: make test-race
